# All card text fields use {"en": "...", "es": "..."} so the same deck can be
# rendered in either language on the client side.

CHALLENGE_CARDS = [
    {
        "id": "ch_01",
        "type": "challenge",
        "title": {"en": "Steady Hands", "es": "Pulso Firme"},
        "description": {
            "en": "Balance a coin on your nose for 10 seconds without it falling.",
            "es": "Equilibra una moneda sobre tu nariz por 10 segundos sin que se caiga.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_02",
        "type": "challenge",
        "title": {"en": "Twisted Tongue", "es": "Trabalenguas"},
        "description": {
            "en": "Say 'She sells seashells by the seashore' three times fast without messing up.",
            "es": "Di 'tres tristes tigres tragaban trigo en un trigal' tres veces rápido sin trabarte.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_03",
        "type": "challenge",
        "title": {"en": "Iron Body", "es": "Cuerpo de Acero"},
        "description": {
            "en": "Hold a perfect plank position for 30 seconds. No sagging, no cheating.",
            "es": "Mantén una plancha perfecta por 30 segundos. Sin caer la cadera, sin trampas.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_04",
        "type": "challenge",
        "title": {"en": "Spin Zone", "es": "Zona de Vueltas"},
        "description": {
            "en": "Spin around 5 times with your eyes closed, then walk in a perfectly straight line.",
            "es": "Da 5 vueltas con los ojos cerrados, después camina en línea perfectamente recta.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_05",
        "type": "challenge",
        "title": {"en": "Wild Animal", "es": "Animal Salvaje"},
        "description": {
            "en": "Imitate an animal of the group's choice for 30 full seconds without stopping.",
            "es": "Imita un animal que elija el grupo durante 30 segundos completos sin parar.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_06",
        "type": "challenge",
        "title": {"en": "Sing It", "es": "A Cantar"},
        "description": {
            "en": "Sing the full chorus of any song of your choice out loud — no humming.",
            "es": "Canta el coro completo de la canción que tú elijas en voz alta — nada de tararear.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_07",
        "type": "challenge",
        "title": {"en": "Robot Mode", "es": "Modo Robot"},
        "description": {
            "en": "Do your best robot dance for 20 full seconds. Group votes if it counts.",
            "es": "Haz tu mejor baile de robot durante 20 segundos. El grupo vota si cuenta.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_08",
        "type": "challenge",
        "title": {"en": "Alphabet Backwards", "es": "Abecedario al Revés"},
        "description": {
            "en": "Say the entire alphabet backwards in under 30 seconds. One mistake and you're done.",
            "es": "Di todo el abecedario al revés en menos de 30 segundos. Un error y pierdes.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_09",
        "type": "challenge",
        "title": {"en": "Wall Sit", "es": "Sentadilla en Pared"},
        "description": {
            "en": "Hold a wall sit (90-degree angle) for 30 seconds. No pushing off the wall.",
            "es": "Mantén una sentadilla contra la pared (ángulo de 90°) por 30 segundos. Sin empujarte de la pared.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_10",
        "type": "challenge",
        "title": {"en": "Who Am I?", "es": "¿Quién Soy?"},
        "description": {
            "en": "Imitate someone in the room until the group correctly guesses who you're impersonating.",
            "es": "Imita a alguien del grupo hasta que adivinen correctamente a quién estás imitando.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_11",
        "type": "challenge",
        "title": {"en": "Red Lorry", "es": "Pablito Clavó"},
        "description": {
            "en": "Say 'red lorry, yellow lorry' five times fast. One slip and you drink.",
            "es": "Di 'Pablito clavó un clavito, ¿qué clavito clavó Pablito?' cinco veces rápido. Un tropiezo y tomas.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_12",
        "type": "challenge",
        "title": {"en": "Jump Squad", "es": "Salto Total"},
        "description": {
            "en": "Do 15 jumping jacks in a row without stopping. No half-reps.",
            "es": "Haz 15 jumping jacks seguidos sin parar. Nada de medias repeticiones.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_13",
        "type": "challenge",
        "title": {"en": "Flamingo", "es": "Flamenco"},
        "description": {
            "en": "Balance on one foot for 30 seconds without touching anything for support.",
            "es": "Mantén el equilibrio en un solo pie por 30 segundos sin apoyarte en nada.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_14",
        "type": "challenge",
        "title": {"en": "Geography Genius", "es": "Genio Geográfico"},
        "description": {
            "en": "Name 10 different countries in 15 seconds. Group decides if they count.",
            "es": "Nombra 10 países distintos en 15 segundos. El grupo decide si cuentan.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_15",
        "type": "challenge",
        "title": {"en": "Runway Walk", "es": "Pasarela"},
        "description": {
            "en": "Do a full catwalk across the room and back like a supermodel. Own it.",
            "es": "Camina como supermodelo por toda la sala, ida y vuelta. Hazlo con actitud.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_16",
        "type": "challenge",
        "title": {"en": "Mystery Tune", "es": "Melodía Misteriosa"},
        "description": {
            "en": "Whistle a song while others try to guess it. If nobody guesses in 30 seconds, you drink.",
            "es": "Silba una canción mientras los demás intentan adivinarla. Si nadie acierta en 30 segundos, tomas.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_17",
        "type": "challenge",
        "title": {"en": "Breath Control", "es": "Control de Respiración"},
        "description": {
            "en": "Hold your breath for a full 20 seconds. Group counts out loud.",
            "es": "Aguanta la respiración por 20 segundos completos. El grupo cuenta en voz alta.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_18",
        "type": "challenge",
        "title": {"en": "Drama Star", "es": "Estrella del Drama"},
        "description": {
            "en": "Give a dramatic 20-second monologue about any mundane part of your day.",
            "es": "Haz un monólogo dramático de 20 segundos sobre cualquier parte aburrida de tu día.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_19",
        "type": "challenge",
        "title": {"en": "Burpee Time", "es": "Hora del Burpee"},
        "description": {
            "en": "Do 5 clean burpees right now. Chest to floor, full jump. No shortcuts.",
            "es": "Haz 5 burpees limpios ahora mismo. Pecho al piso, salto completo. Sin atajos.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_20",
        "type": "challenge",
        "title": {"en": "Fame Drop", "es": "Cascada de Fama"},
        "description": {
            "en": "Name 10 different celebrities in 15 seconds. Group votes on if they're real.",
            "es": "Nombra 10 celebridades distintas en 15 segundos. El grupo vota si son reales.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_21",
        "type": "challenge",
        "title": {"en": "The Worm", "es": "El Gusano"},
        "description": {
            "en": "Do the worm across the floor — or at least a sincere attempt. Group decides.",
            "es": "Haz el gusano por el piso — o al menos un intento sincero. El grupo decide.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_22",
        "type": "challenge",
        "title": {"en": "Elbow Catch", "es": "Atrapada de Codo"},
        "description": {
            "en": "Stack 5 coins on your elbow and swing your arm to catch them all in one move.",
            "es": "Apila 5 monedas en tu codo y mueve el brazo para atraparlas todas de un solo golpe.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_23",
        "type": "challenge",
        "title": {"en": "Unique New York", "es": "El Cielo Enladrillado"},
        "description": {
            "en": "Say 'unique New York' five times fast without stumbling once.",
            "es": "Di 'el cielo está enladrillado, ¿quién lo desenladrillará?' cinco veces rápido sin trabarte.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_24",
        "type": "challenge",
        "title": {"en": "Moonwalk", "es": "Moonwalk"},
        "description": {
            "en": "Do your best Michael Jackson moonwalk across the room. Technique counts.",
            "es": "Haz tu mejor moonwalk al estilo Michael Jackson cruzando la sala. La técnica cuenta.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_25",
        "type": "challenge",
        "title": {"en": "Head Balancer", "es": "Balance en la Cabeza"},
        "description": {
            "en": "Balance any object from your surroundings on your head for 30 seconds.",
            "es": "Equilibra cualquier objeto a tu alrededor sobre tu cabeza por 30 segundos.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_26",
        "type": "challenge",
        "title": {"en": "Squat Squad", "es": "Escuadrón de Sentadillas"},
        "description": {
            "en": "Do 10 full squats in a row with proper form. Thighs parallel or you redo it.",
            "es": "Haz 10 sentadillas completas seguidas con buena forma. Muslos paralelos o las repites.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_27",
        "type": "challenge",
        "title": {"en": "Nursery Rhyme", "es": "Rima Infantil"},
        "description": {
            "en": "Recite any nursery rhyme fully from memory. No pausing, no helping.",
            "es": "Recita cualquier canción o rima infantil completa de memoria. Sin pausas, sin ayuda.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_28",
        "type": "challenge",
        "title": {"en": "Hype Dance", "es": "Baile Energético"},
        "description": {
            "en": "Do your most energetic hype dance move for 15 full seconds. Go all in.",
            "es": "Haz tu paso de baile más energético por 15 segundos completos. Da todo.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_29",
        "type": "challenge",
        "title": {"en": "Core Challenge", "es": "Reto de Abdomen"},
        "description": {
            "en": "Do 10 proper sit-ups in a row. Hands behind your head, back to floor each rep.",
            "es": "Haz 10 abdominales bien hechos seguidos. Manos detrás de la cabeza, espalda al piso en cada repetición.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_30",
        "type": "challenge",
        "title": {"en": "Comedian", "es": "Comediante"},
        "description": {
            "en": "Make at least one person in the group genuinely laugh in 30 seconds.",
            "es": "Haz que al menos una persona del grupo se ría de verdad en 30 segundos.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_31",
        "type": "challenge",
        "title": {"en": "Push-Up Power", "es": "Poder de Lagartijas"},
        "description": {
            "en": "Bang out 10 clean push-ups right now. Chest to the floor each rep, no half-reps.",
            "es": "Haz 10 lagartijas limpias ahora mismo. Pecho al piso en cada una, sin medias repeticiones.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_32",
        "type": "challenge",
        "title": {"en": "Air Guitar", "es": "Guitarra Aérea"},
        "description": {
            "en": "Play an absolutely shameless air guitar solo for 20 seconds. Sound effects required.",
            "es": "Toca un solo de guitarra aérea sin ninguna vergüenza por 20 segundos. Los efectos de sonido son obligatorios.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_33",
        "type": "challenge",
        "title": {"en": "Charades Solo", "es": "Mímica en Solitario"},
        "description": {
            "en": "Act out a movie title in silence. The group has 30 seconds to guess it correctly.",
            "es": "Actúa el título de una película en silencio. El grupo tiene 30 segundos para adivinarlo correctamente.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_34",
        "type": "challenge",
        "title": {"en": "Freestyle Rap", "es": "Rap Freestyle"},
        "description": {
            "en": "Drop a 15-second freestyle rap about everyone in the room. Bars must rhyme.",
            "es": "Suelta un freestyle de rap de 15 segundos sobre todos los del grupo. Las rimas son obligatorias.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_35",
        "type": "challenge",
        "title": {"en": "Backwards Counter", "es": "Conteo Inverso"},
        "description": {
            "en": "Count from 100 down to 80 out loud in under 20 seconds. No skipping numbers.",
            "es": "Cuenta de 100 a 80 en voz alta en menos de 20 segundos. Sin saltarte números.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_36",
        "type": "challenge",
        "title": {"en": "Crab Walk", "es": "Caminata de Cangrejo"},
        "description": {
            "en": "Crab walk from one wall of the room to the other. No collapsing halfway.",
            "es": "Camina como cangrejo de una pared de la sala a la otra. Sin desplomarte a la mitad.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_37",
        "type": "challenge",
        "title": {"en": "Dance Off", "es": "Batalla de Baile"},
        "description": {
            "en": "Pick a player and challenge them to a 30-second dance battle. The group decides who lost.",
            "es": "Escoge un jugador y rétalo a una batalla de baile de 30 segundos. El grupo decide quién pierde.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_38",
        "type": "challenge",
        "title": {"en": "Memory Test", "es": "Prueba de Memoria"},
        "description": {
            "en": "Group names 5 random objects out loud. You repeat them back in order without missing one.",
            "es": "El grupo dice 5 objetos aleatorios en voz alta. Tú los repites en orden sin fallar ninguno.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_39",
        "type": "challenge",
        "title": {"en": "Color Hunt", "es": "Caza de Colores"},
        "description": {
            "en": "Find 5 things in the room of the exact same color in 15 seconds. Group picks the color.",
            "es": "Encuentra 5 cosas del mismo color exacto en la sala en 15 segundos. El grupo escoge el color.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_40",
        "type": "challenge",
        "title": {"en": "Compliment Round", "es": "Ronda de Halagos"},
        "description": {
            "en": "Give every single player at the table a unique, genuine compliment in 30 seconds.",
            "es": "Dale a cada jugador del grupo un halago único y genuino en 30 segundos.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_41",
        "type": "challenge",
        "title": {"en": "Air Swim", "es": "Natación Aérea"},
        "description": {
            "en": "Pretend to swim through the air across the room. Pick any stroke, commit fully.",
            "es": "Finge nadar por el aire cruzando la sala. Elige cualquier estilo, comprométete totalmente.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_42",
        "type": "challenge",
        "title": {"en": "Backwards Walk", "es": "Caminata Atrás"},
        "description": {
            "en": "Walk backwards from one wall to the other without looking back or bumping into anything.",
            "es": "Camina hacia atrás de una pared a la otra sin voltear ni chocarte con nada.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_43",
        "type": "challenge",
        "title": {"en": "Blind Drawer", "es": "Dibujante Ciego"},
        "description": {
            "en": "Group picks something for you to draw. You draw it with your eyes closed in 30 seconds.",
            "es": "El grupo escoge algo para que dibujes. Lo dibujas con los ojos cerrados en 30 segundos.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_44",
        "type": "challenge",
        "title": {"en": "Speed Reader", "es": "Lectura Rápida"},
        "description": {
            "en": "Pick up the closest text and read a full paragraph out loud as fast as humanly possible.",
            "es": "Toma el texto más cercano y lee un párrafo completo en voz alta tan rápido como puedas.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_45",
        "type": "challenge",
        "title": {"en": "Mirror Dance", "es": "Baile Espejo"},
        "description": {
            "en": "Mirror every dance move of the player to your right for 20 full seconds. They go wild.",
            "es": "Imita como espejo cada paso de baile del jugador a tu derecha por 20 segundos. Ellos se vuelven locos.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_46",
        "type": "challenge",
        "title": {"en": "Pillow Balance", "es": "Balance de Almohada"},
        "description": {
            "en": "Balance a pillow (or jacket) on your head while turning in a full circle. No hands.",
            "es": "Equilibra una almohada (o chaqueta) sobre tu cabeza mientras das una vuelta completa. Sin manos.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_47",
        "type": "challenge",
        "title": {"en": "Beatbox Beat", "es": "Beatbox"},
        "description": {
            "en": "Lay down a solid beatbox rhythm for 15 straight seconds. No giggling, no breaks.",
            "es": "Suelta un beatbox sólido durante 15 segundos seguidos. Sin risitas, sin pausas.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_48",
        "type": "challenge",
        "title": {"en": "Word Chain", "es": "Cadena de Palabras"},
        "description": {
            "en": "Group picks a letter. You name 10 different words starting with it in 15 seconds.",
            "es": "El grupo elige una letra. Tú dices 10 palabras distintas que empiecen con ella en 15 segundos.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_49",
        "type": "challenge",
        "title": {"en": "One Foot Hop", "es": "Saltos en Un Pie"},
        "description": {
            "en": "Hop on one foot 20 times in a row without putting the other foot down or touching anything.",
            "es": "Salta en un solo pie 20 veces seguidas sin bajar el otro pie ni apoyarte en nada.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_50",
        "type": "challenge",
        "title": {"en": "Italian Mode", "es": "Modo Italiano"},
        "description": {
            "en": "Speak entirely in fake Italian (no real words) for the next 30 seconds. Hand gestures encouraged.",
            "es": "Habla totalmente en italiano falso (nada de palabras reales) por los próximos 30 segundos. Los gestos con las manos son bienvenidos.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_51",
        "type": "challenge",
        "title": {"en": "Air Drums", "es": "Batería Aérea"},
        "description": {
            "en": "Play full air drums to a song someone hums for 20 seconds. Sound effects mandatory.",
            "es": "Toca batería aérea completa a una canción que alguien tararee por 20 segundos. Los efectos de sonido son obligatorios.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_52",
        "type": "challenge",
        "title": {"en": "Story Time", "es": "Hora del Cuento"},
        "description": {
            "en": "Improvise a 30-second spooky story starring everyone in the room. No long pauses allowed.",
            "es": "Improvisa una historia de terror de 30 segundos donde aparezcan todos los del grupo. Sin pausas largas.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_53",
        "type": "challenge",
        "title": {"en": "Movie Quote", "es": "Cita de Película"},
        "description": {
            "en": "Deliver a famous movie quote fully in character. Group must guess the movie. Bad acting = drink.",
            "es": "Recita una cita famosa de película totalmente metido en el personaje. El grupo debe adivinar la película. Mala actuación = tomas.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_54",
        "type": "challenge",
        "title": {"en": "Backwards Name", "es": "Nombre al Revés"},
        "description": {
            "en": "Say your full name backwards out loud, five times in a row. One mess-up and you drink.",
            "es": "Di tu nombre completo al revés en voz alta cinco veces seguidas. Un error y tomas.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_55",
        "type": "challenge",
        "title": {"en": "Knee Touch", "es": "Toca Rodilla"},
        "description": {
            "en": "Touch your right elbow to your left knee, then alternate, 10 times total. Real form only.",
            "es": "Toca tu codo derecho con la rodilla izquierda, luego alterna, 10 veces en total. Solo con buena forma.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_56",
        "type": "challenge",
        "title": {"en": "Slow Mo Battle", "es": "Batalla en Cámara Lenta"},
        "description": {
            "en": "Pick a player. Have a fully slow-motion fight for 20 seconds. Sound effects required.",
            "es": "Escoge un jugador. Tengan una pelea totalmente en cámara lenta por 20 segundos. Efectos de sonido obligatorios.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_57",
        "type": "challenge",
        "title": {"en": "Whisper Confession", "es": "Confesión Susurrada"},
        "description": {
            "en": "Whisper a fake outrageous secret loud enough that everyone in the room can hear it.",
            "es": "Susurra un secreto inventado y escandaloso lo suficientemente fuerte para que todos en la sala lo escuchen.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_58",
        "type": "challenge",
        "title": {"en": "Yoga Tree", "es": "Árbol de Yoga"},
        "description": {
            "en": "Hold the yoga tree pose (one foot to inner thigh, hands up) for 30 seconds. No wobbling.",
            "es": "Mantén la postura del árbol de yoga (un pie al muslo interno, manos arriba) por 30 segundos. Sin tambalearte.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "ch_59",
        "type": "challenge",
        "title": {"en": "Shadow Boxing", "es": "Boxeo de Sombras"},
        "description": {
            "en": "Shadow box hard for 20 full seconds — jabs, hooks, dodges. Don't drop your hands.",
            "es": "Haz boxeo de sombra fuerte por 20 segundos completos — jabs, ganchos, esquivadas. No bajes las manos.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "ch_60",
        "type": "challenge",
        "title": {"en": "Hum Tune", "es": "Tararea Melodía"},
        "description": {
            "en": "Hum a popular song while the group tries to guess it. If nobody gets it in 30 seconds, you drink.",
            "es": "Tararea una canción conocida mientras el grupo intenta adivinarla. Si nadie acierta en 30 segundos, tomas.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
]

TRUTH_CARDS = [
    {
        "id": "tr_01",
        "type": "truth",
        "title": {"en": "Public Shame", "es": "Vergüenza Pública"},
        "description": {
            "en": "What's the most embarrassing thing you've done in public? Give full details.",
            "es": "¿Cuál es la cosa más vergonzosa que has hecho en público? Cuenta todos los detalles.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_02",
        "type": "truth",
        "title": {"en": "Dating Lies", "es": "Mentiras de Citas"},
        "description": {
            "en": "Have you ever lied to get out of a date? What was the lie and who was the victim?",
            "es": "¿Alguna vez mentiste para zafarte de una cita? ¿Cuál fue la mentira y quién fue la víctima?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_03",
        "type": "truth",
        "title": {"en": "Worst Date Ever", "es": "Peor Cita"},
        "description": {
            "en": "Describe the absolute worst date you've ever been on. What made it so terrible?",
            "es": "Describe la peor cita que has tenido en tu vida. ¿Qué la hizo tan terrible?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_04",
        "type": "truth",
        "title": {"en": "Social Stalker", "es": "Stalker Social"},
        "description": {
            "en": "Have you ever stalked someone's social media for more than an hour straight? Who and why?",
            "es": "¿Alguna vez stalkeaste las redes de alguien por más de una hora seguida? ¿A quién y por qué?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_05",
        "type": "truth",
        "title": {"en": "Search History", "es": "Historial de Búsqueda"},
        "description": {
            "en": "What's the most embarrassing thing currently in your search history? No lying.",
            "es": "¿Qué es lo más vergonzoso que tienes ahora mismo en tu historial de búsqueda? Sin mentir.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_06",
        "type": "truth",
        "title": {"en": "Wrong Text", "es": "Mensaje Equivocado"},
        "description": {
            "en": "Have you ever sent a message to the completely wrong person? What did it say?",
            "es": "¿Alguna vez le mandaste un mensaje a la persona totalmente equivocada? ¿Qué decía?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_07",
        "type": "truth",
        "title": {"en": "Parent Lies", "es": "Mentiras a los Papás"},
        "description": {
            "en": "What's the biggest lie you've ever told your parents? Did they ever find out?",
            "es": "¿Cuál es la mentira más grande que les has dicho a tus papás? ¿Se enteraron?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_08",
        "type": "truth",
        "title": {"en": "Pool Confession", "es": "Confesión en la Piscina"},
        "description": {
            "en": "Have you ever peed in a pool or a body of water? Be completely honest.",
            "es": "¿Alguna vez has hecho pis en una piscina o en algún cuerpo de agua? Sé totalmente honesto.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_09",
        "type": "truth",
        "title": {"en": "Forever Young", "es": "Por Siempre Joven"},
        "description": {
            "en": "What's the most childish thing you still secretly do that you'd be embarrassed if people knew?",
            "es": "¿Cuál es la cosa más infantil que sigues haciendo en secreto y que te daría vergüenza que supieran?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_10",
        "type": "truth",
        "title": {"en": "Forbidden Crush", "es": "Crush Prohibido"},
        "description": {
            "en": "Have you ever had romantic feelings for a close friend's significant other?",
            "es": "¿Alguna vez has tenido sentimientos románticos por la pareja de un amigo cercano?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_11",
        "type": "truth",
        "title": {"en": "Drunk Story", "es": "Historia de Borracho"},
        "description": {
            "en": "What's the most embarrassing thing you've done while drunk? Full story.",
            "es": "¿Cuál es la cosa más vergonzosa que has hecho borracho? Cuenta toda la historia.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_12",
        "type": "truth",
        "title": {"en": "Academic Crime", "es": "Crimen Académico"},
        "description": {
            "en": "Have you ever cheated on a test, exam, or major assignment? Tell the story.",
            "es": "¿Alguna vez has copiado en una prueba, examen o trabajo importante? Cuenta la historia.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_13",
        "type": "truth",
        "title": {"en": "Home Alone Weirdness", "es": "Rarezas en Casa"},
        "description": {
            "en": "What's the weirdest thing you do when you're completely alone at home?",
            "es": "¿Cuál es la cosa más rara que haces cuando estás totalmente solo en casa?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_14",
        "type": "truth",
        "title": {"en": "Ghost Mode", "es": "Modo Fantasma"},
        "description": {
            "en": "Have you ever ghosted someone you actually had feelings for? What happened?",
            "es": "¿Alguna vez le has hecho ghosting a alguien que realmente te gustaba? ¿Qué pasó?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_15",
        "type": "truth",
        "title": {"en": "Guilty Playlist", "es": "Playlist Culposa"},
        "description": {
            "en": "What's the most embarrassing song you genuinely love and listen to on repeat?",
            "es": "¿Cuál es la canción más vergonzosa que realmente amas y escuchas en repeat?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_16",
        "type": "truth",
        "title": {"en": "Fake Laugh", "es": "Risa Falsa"},
        "description": {
            "en": "When was the last time you pretended to laugh at a joke you didn't understand at all?",
            "es": "¿Cuándo fue la última vez que fingiste reírte de un chiste que no entendiste para nada?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_17",
        "type": "truth",
        "title": {"en": "Behind The Back", "es": "Por la Espalda"},
        "description": {
            "en": "What's the worst thing you've ever said about someone in this room behind their back?",
            "es": "¿Cuál es la peor cosa que has dicho de alguien de este grupo por la espalda?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_18",
        "type": "truth",
        "title": {"en": "Wrong Bathroom", "es": "Baño Equivocado"},
        "description": {
            "en": "Have you ever accidentally walked into the wrong bathroom? Tell the whole story.",
            "es": "¿Alguna vez te metiste por accidente al baño equivocado? Cuenta toda la historia.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_19",
        "type": "truth",
        "title": {"en": "Dirty Habit", "es": "Hábito Sucio"},
        "description": {
            "en": "What habit are you most embarrassed about? Something you'd never admit sober.",
            "es": "¿De qué hábito te avergüenzas más? Algo que jamás admitirías sobrio.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_20",
        "type": "truth",
        "title": {"en": "Awkward Nap", "es": "Siesta Incómoda"},
        "description": {
            "en": "Have you ever fallen asleep somewhere truly embarrassing or inappropriate? Where?",
            "es": "¿Alguna vez te quedaste dormido en un lugar realmente vergonzoso o inapropiado? ¿Dónde?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_21",
        "type": "truth",
        "title": {"en": "Cringe Moment", "es": "Momento Cringe"},
        "description": {
            "en": "What's the most awkward social situation you've ever been stuck in?",
            "es": "¿Cuál es la situación social más incómoda en la que has estado atrapado?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_22",
        "type": "truth",
        "title": {"en": "Accidental Like", "es": "Like Accidental"},
        "description": {
            "en": "Have you ever accidentally liked a very old post while deep-stalking someone online?",
            "es": "¿Alguna vez le diste like sin querer a un post muy viejo mientras stalkeabas profundamente a alguien?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_23",
        "type": "truth",
        "title": {"en": "Photo Shame", "es": "Foto Vergonzosa"},
        "description": {
            "en": "Describe the most embarrassing photo of you that exists somewhere right now.",
            "es": "Describe la foto más vergonzosa tuya que existe en algún lado ahora mismo.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_24",
        "type": "truth",
        "title": {"en": "Age Faker", "es": "Mintiendo la Edad"},
        "description": {
            "en": "Have you ever lied about your age to get into somewhere or impress someone?",
            "es": "¿Alguna vez has mentido sobre tu edad para entrar a algún lugar o impresionar a alguien?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_25",
        "type": "truth",
        "title": {"en": "Old But Gold", "es": "Viejo pero Bueno"},
        "description": {
            "en": "What's something you're definitely too old for but still secretly enjoy doing?",
            "es": "¿Qué cosa haces que claramente eres demasiado grande para ella, pero aún así disfrutas en secreto?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_26",
        "type": "truth",
        "title": {"en": "Caught Red-Handed", "es": "Cachado en el Acto"},
        "description": {
            "en": "What's the most embarrassing thing you've been caught doing that you had no excuse for?",
            "es": "¿Cuál es la cosa más vergonzosa que te han cachado haciendo y no tenías excusa?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_27",
        "type": "truth",
        "title": {"en": "Terrible Gift", "es": "Regalo Terrible"},
        "description": {
            "en": "What's the most thoughtless or terrible gift you've ever given someone? Who got it?",
            "es": "¿Cuál es el regalo más feo o desconsiderado que le has dado a alguien? ¿Quién lo recibió?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_28",
        "type": "truth",
        "title": {"en": "Soft Heart", "es": "Corazón Blando"},
        "description": {
            "en": "What movie, TV show, or book made you cry that most people would find embarrassing?",
            "es": "¿Qué película, serie o libro te hizo llorar que para los demás sería vergonzoso?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_29",
        "type": "truth",
        "title": {"en": "Attention Seeker", "es": "En Busca de Atención"},
        "description": {
            "en": "What's the most desperate thing you've ever done to get someone's attention?",
            "es": "¿Cuál es la cosa más desesperada que has hecho para llamar la atención de alguien?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_30",
        "type": "truth",
        "title": {"en": "Celebrity Claim", "es": "Falso Famoso"},
        "description": {
            "en": "Have you ever pretended to personally know a celebrity or famous person?",
            "es": "¿Alguna vez has fingido conocer personalmente a una celebridad o persona famosa?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_31",
        "type": "truth",
        "title": {"en": "First Crush", "es": "Primer Amor"},
        "description": {
            "en": "Who was your first real crush and what's the cringiest thing you did to get noticed?",
            "es": "¿Quién fue tu primer amor real y qué es la cosa más cringe que hiciste para que se fijara en ti?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_32",
        "type": "truth",
        "title": {"en": "Drunk Text", "es": "Mensaje de Borracho"},
        "description": {
            "en": "What's the wildest text you've ever sent while drunk and to who? No skipping details.",
            "es": "¿Cuál es el mensaje más loco que has mandado borracho y a quién? Sin saltarte detalles.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_33",
        "type": "truth",
        "title": {"en": "Pet Peeve", "es": "Mayor Molestia"},
        "description": {
            "en": "What's something a person in this room does that secretly drives you absolutely insane?",
            "es": "¿Qué es algo que hace una persona de este grupo que secretamente te vuelve totalmente loco?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_34",
        "type": "truth",
        "title": {"en": "Worst Job", "es": "Peor Trabajo"},
        "description": {
            "en": "What's the worst job you've ever had and what was your biggest disaster on it?",
            "es": "¿Cuál es el peor trabajo que has tenido y cuál fue tu mayor desastre en él?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_35",
        "type": "truth",
        "title": {"en": "Faked Sick", "es": "Enfermo Falso"},
        "description": {
            "en": "When was the last time you faked being sick to skip something? What did you do instead?",
            "es": "¿Cuándo fue la última vez que fingiste estar enfermo para zafarte de algo? ¿Qué hiciste en su lugar?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_36",
        "type": "truth",
        "title": {"en": "Childhood Fear", "es": "Miedo de Niño"},
        "description": {
            "en": "What's an irrational childhood fear that still secretly creeps you out as an adult?",
            "es": "¿Cuál es un miedo irracional de la infancia que todavía secretamente te asusta de adulto?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_37",
        "type": "truth",
        "title": {"en": "Stupid Injury", "es": "Lesión Tonta"},
        "description": {
            "en": "What's the dumbest way you've ever injured yourself? Walk us through every step.",
            "es": "¿Cuál es la forma más tonta en la que te has lesionado? Cuéntanos paso a paso.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_38",
        "type": "truth",
        "title": {"en": "Active Lie", "es": "Mentira Activa"},
        "description": {
            "en": "What's a big lie you're still currently telling someone — and to who?",
            "es": "¿Cuál es una mentira grande que sigues diciéndole a alguien actualmente — y a quién?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_39",
        "type": "truth",
        "title": {"en": "Crying In Public", "es": "Llorando en Público"},
        "description": {
            "en": "When was the last time you cried in public, and what set it off? Be specific.",
            "es": "¿Cuándo fue la última vez que lloraste en público y qué lo provocó? Sé específico.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_40",
        "type": "truth",
        "title": {"en": "Trash Decision", "es": "Decisión de Basura"},
        "description": {
            "en": "What's the dumbest decision you've made in the past year and how badly did it backfire?",
            "es": "¿Cuál es la decisión más tonta que tomaste el último año y qué tan mal salió?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_41",
        "type": "truth",
        "title": {"en": "Friend Crush", "es": "Crush de Amigo"},
        "description": {
            "en": "Have you ever had a secret crush on a close friend? Did anything ever happen?",
            "es": "¿Alguna vez tuviste un crush secreto con un amigo cercano? ¿Llegó a pasar algo?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_42",
        "type": "truth",
        "title": {"en": "Top Stalker", "es": "Top Stalker"},
        "description": {
            "en": "Whose social media do you check most often? Be brutally honest, no excuses.",
            "es": "¿A quién le revisas las redes con más frecuencia? Sé brutalmente honesto, sin excusas.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_43",
        "type": "truth",
        "title": {"en": "Drunk Calls", "es": "Llamadas de Borracho"},
        "description": {
            "en": "Who was the last person you drunk-called and what did you say to them?",
            "es": "¿Quién fue la última persona a la que llamaste borracho y qué le dijiste?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_44",
        "type": "truth",
        "title": {"en": "Regret Tattoo", "es": "Tatuaje Arrepentido"},
        "description": {
            "en": "If you had to get a tattoo of one thing you've Googled this week, what would it be?",
            "es": "Si tuvieras que hacerte un tatuaje de algo que hayas googleado esta semana, ¿qué sería?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_45",
        "type": "truth",
        "title": {"en": "Failed Audition", "es": "Audición Fallida"},
        "description": {
            "en": "Tell us about a time you tried hard at something and embarrassingly, publicly failed.",
            "es": "Cuéntanos de una vez que te esforzaste en algo y fallaste vergonzosamente en público.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_46",
        "type": "truth",
        "title": {"en": "Dance Floor Crime", "es": "Crimen en la Pista"},
        "description": {
            "en": "What's the cringiest move you've ever pulled on a dance floor in front of people?",
            "es": "¿Cuál es el paso más cringe que has hecho en una pista de baile delante de la gente?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_47",
        "type": "truth",
        "title": {"en": "Public Argument", "es": "Pelea en Público"},
        "description": {
            "en": "When was the last time you had a public argument and what was it actually about?",
            "es": "¿Cuándo fue la última vez que tuviste una pelea en público y de qué fue realmente?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_48",
        "type": "truth",
        "title": {"en": "Body Swap Wish", "es": "Cambio Corporal"},
        "description": {
            "en": "If you could swap one body feature with anyone in this room, whose and which one?",
            "es": "Si pudieras cambiar una característica corporal con alguien de este grupo, ¿de quién y cuál?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_49",
        "type": "truth",
        "title": {"en": "Bad Roommate", "es": "Mal Compañero de Cuarto"},
        "description": {
            "en": "What's the worst roommate behavior you've personally been guilty of? Spare no detail.",
            "es": "¿Cuál es el peor comportamiento de compañero de cuarto del que tú has sido culpable? Sin omitir detalles.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_50",
        "type": "truth",
        "title": {"en": "Talking To Self", "es": "Hablándote Solo"},
        "description": {
            "en": "What's something you've been caught saying out loud to yourself that you can't deny?",
            "es": "¿Qué es algo que te han cachado diciéndote a ti mismo en voz alta y no puedes negar?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_51",
        "type": "truth",
        "title": {"en": "Silent Treatment", "es": "Ley del Hielo"},
        "description": {
            "en": "What's the longest you've ever ignored someone on purpose, and what set it off?",
            "es": "¿Cuál es el tiempo más largo que has ignorado a alguien a propósito y qué lo provocó?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_52",
        "type": "truth",
        "title": {"en": "Stolen Moment", "es": "Momento Robado"},
        "description": {
            "en": "Have you ever stolen anything in your life — even something small? What was it?",
            "es": "¿Alguna vez has robado algo en tu vida — aunque sea algo pequeño? ¿Qué fue?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_53",
        "type": "truth",
        "title": {"en": "Creepy Search", "es": "Búsqueda Rara"},
        "description": {
            "en": "What's the weirdest thing you've Googled in the past month? No editing the truth.",
            "es": "¿Cuál es la cosa más rara que has googleado en el último mes? Sin editar la verdad.",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_54",
        "type": "truth",
        "title": {"en": "Awkward Hug", "es": "Abrazo Incómodo"},
        "description": {
            "en": "Tell the story of the most awkward hug you've ever been part of. Who was it with?",
            "es": "Cuenta la historia del abrazo más incómodo del que has sido parte. ¿Con quién fue?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_55",
        "type": "truth",
        "title": {"en": "Petty Revenge", "es": "Venganza Mezquina"},
        "description": {
            "en": "What's the pettiest revenge you've ever pulled on someone who deserved it?",
            "es": "¿Cuál es la venganza más mezquina que le has hecho a alguien que se lo merecía?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_56",
        "type": "truth",
        "title": {"en": "Worst Outfit", "es": "Peor Atuendo"},
        "description": {
            "en": "Describe the worst outfit you ever wore in public with full confidence at the time.",
            "es": "Describe el peor atuendo que usaste en público y con total confianza en su momento.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_57",
        "type": "truth",
        "title": {"en": "Pet Talk", "es": "Hablar con Mascota"},
        "description": {
            "en": "What's something you say to your pet (or would say) that nobody should ever hear?",
            "es": "¿Qué es algo que le dices a tu mascota (o le dirías) que nadie debería escuchar nunca?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_58",
        "type": "truth",
        "title": {"en": "Gym Lie", "es": "Mentira de Gym"},
        "description": {
            "en": "When was the last time you skipped the gym and lied about working out? Whose face did you lie to?",
            "es": "¿Cuándo fue la última vez que te saltaste el gym y mentiste sobre haber entrenado? ¿A quién?",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
    {
        "id": "tr_59",
        "type": "truth",
        "title": {"en": "Rejected Plans", "es": "Planes Rechazados"},
        "description": {
            "en": "What's the most recent plan you flaked on with a totally fake excuse? What did you actually do?",
            "es": "¿Cuál fue el plan más reciente al que le bajaste con una excusa totalmente falsa? ¿Qué hiciste realmente?",
        },
        "consequence": {"en": "Drink half your glass.", "es": "Tómate medio vaso."},
        "drink_amount": "half_glass",
    },
    {
        "id": "tr_60",
        "type": "truth",
        "title": {"en": "Wallpaper Reveal", "es": "Fondo Revelado"},
        "description": {
            "en": "Show your phone wallpaper right now and explain why on earth you picked it.",
            "es": "Muestra el fondo de pantalla de tu celular ahora mismo y explica por qué lo escogiste.",
        },
        "consequence": {"en": "Take a full shot.", "es": "Tómate un shot completo."},
        "drink_amount": "shot",
    },
]

RULE_CARDS = [
    {
        "id": "ru_01",
        "type": "rule",
        "title": {"en": "No Real Names", "es": "Sin Nombres Reales"},
        "description": {
            "en": "No one can use anyone's real name for the next 3 rounds. Invent a nickname for everyone right now. Anyone who slips up drinks.",
            "es": "Nadie puede usar el nombre real de nadie por las próximas 3 rondas. Inventen un apodo para cada uno ahora mismo. Quien se equivoque, toma.",
        },
        "consequence": {"en": "Slip up and drink.", "es": "Si te equivocas, tomas."},
        "rounds": 3,
    },
    {
        "id": "ru_02",
        "type": "rule",
        "title": {"en": "Whisper Mode", "es": "Modo Susurro"},
        "description": {
            "en": "Everyone must whisper for the next 2 full rounds. Speaking at normal volume means you drink immediately.",
            "es": "Todos deben susurrar por las próximas 2 rondas completas. Hablar a volumen normal significa que tomas inmediatamente.",
        },
        "consequence": {"en": "Normal volume costs a drink.", "es": "Volumen normal cuesta un trago."},
        "rounds": 2,
    },
    {
        "id": "ru_03",
        "type": "rule",
        "title": {"en": "Elbow Pointers Only", "es": "Apuntar con Codo"},
        "description": {
            "en": "No pointing with fingers for the next 3 rounds. Use your elbow to point. Anyone who points with a finger drinks.",
            "es": "Nada de apuntar con los dedos por las próximas 3 rondas. Usen el codo para apuntar. Quien apunte con un dedo, toma.",
        },
        "consequence": {"en": "Finger pointer drinks.", "es": "Quien apunte con dedo, toma."},
        "rounds": 3,
    },
    {
        "id": "ru_04",
        "type": "rule",
        "title": {"en": "In Bed Rule", "es": "Regla en la Cama"},
        "description": {
            "en": "Everyone must add 'in bed' to the end of every single sentence for the next 2 rounds.",
            "es": "Todos deben agregar 'en la cama' al final de cada oración por las próximas 2 rondas.",
        },
        "consequence": {"en": "Forget and drink.", "es": "Si olvidas, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_05",
        "type": "rule",
        "title": {"en": "No Laughing", "es": "Sin Reír"},
        "description": {
            "en": "Absolutely no laughing allowed for the next 2 rounds. Anyone who laughs — even smiles — must drink.",
            "es": "Absolutamente nada de reírse por las próximas 2 rondas. Quien se ría — incluso si solo sonríe — debe tomar.",
        },
        "consequence": {"en": "Laugh and you drink.", "es": "Te ríes y tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_06",
        "type": "rule",
        "title": {"en": "Accent Time", "es": "Hora del Acento"},
        "description": {
            "en": "Everyone must pick an accent right now and speak in it for the next 3 rounds. Dropping the accent means a drink.",
            "es": "Todos deben elegir un acento ahora mismo y hablar con él por las próximas 3 rondas. Soltar el acento significa tomar.",
        },
        "consequence": {"en": "Drop the accent, drink.", "es": "Si sueltas el acento, tomas."},
        "rounds": 3,
    },
    {
        "id": "ru_07",
        "type": "rule",
        "title": {"en": "Left Hand Only", "es": "Solo Mano Izquierda"},
        "description": {
            "en": "All drinks must be taken with the left hand for the next 3 rounds. Using the right hand means you drink again with the left.",
            "es": "Todas las bebidas deben tomarse con la mano izquierda por las próximas 3 rondas. Usar la derecha significa que tomas otra vez con la izquierda.",
        },
        "consequence": {"en": "Wrong hand? Drink again.", "es": "¿Mano equivocada? Toma de nuevo."},
        "rounds": 3,
    },
    {
        "id": "ru_08",
        "type": "rule",
        "title": {"en": "May I Please?", "es": "¿Me Permiten?"},
        "description": {
            "en": "No one may take a sip of any drink without first saying 'May I please have a sip?' for the next 2 rounds.",
            "es": "Nadie puede dar un sorbo sin antes decir '¿Me permiten un sorbo?' por las próximas 2 rondas.",
        },
        "consequence": {"en": "Skip the phrase, drink twice.", "es": "Si te saltas la frase, tomas dos veces."},
        "rounds": 2,
    },
    {
        "id": "ru_09",
        "type": "rule",
        "title": {"en": "Stand to Speak", "es": "De Pie para Hablar"},
        "description": {
            "en": "For the next 2 rounds, anyone who wants to talk must stand up first. Speak while seated and you drink.",
            "es": "Por las próximas 2 rondas, quien quiera hablar debe pararse primero. Hablar sentado significa tomar.",
        },
        "consequence": {"en": "Sit and speak? Drink up.", "es": "¿Hablar sentado? A tomar."},
        "rounds": 2,
    },
    {
        "id": "ru_10",
        "type": "rule",
        "title": {"en": "Banned Words", "es": "Palabras Prohibidas"},
        "description": {
            "en": "The words 'drink' and 'shot' are completely banned for the next 3 rounds. Invent code words. Anyone who slips drinks.",
            "es": "Las palabras 'tomar' y 'shot' están totalmente prohibidas por las próximas 3 rondas. Inventen palabras clave. Quien se equivoque, toma.",
        },
        "consequence": {"en": "Say the word, drink.", "es": "Si dices la palabra, tomas."},
        "rounds": 3,
    },
    {
        "id": "ru_11",
        "type": "rule",
        "title": {"en": "Rhyme Time", "es": "Hora de Rimar"},
        "description": {
            "en": "Every sentence must rhyme with the last word of the previous speaker for the next 2 rounds. Fail and drink.",
            "es": "Cada oración debe rimar con la última palabra del que habló antes por las próximas 2 rondas. Si fallas, tomas.",
        },
        "consequence": {"en": "No rhyme, drink.", "es": "Sin rima, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_12",
        "type": "rule",
        "title": {"en": "Robot Speak", "es": "Hablar Como Robot"},
        "description": {
            "en": "Everyone must speak in a robotic, monotone voice for the next 2 rounds. Going human costs a drink.",
            "es": "Todos deben hablar con voz robótica y monótona por las próximas 2 rondas. Sonar humano cuesta un trago.",
        },
        "consequence": {"en": "Break character, drink.", "es": "Si rompes el personaje, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_13",
        "type": "rule",
        "title": {"en": "Slow Motion", "es": "Cámara Lenta"},
        "description": {
            "en": "Every physical movement must be done in slow motion for the entire next round. Speed up and you drink.",
            "es": "Todo movimiento físico debe hacerse en cámara lenta durante toda la próxima ronda. Si te aceleras, tomas.",
        },
        "consequence": {"en": "Move too fast, drink.", "es": "Te mueves muy rápido, tomas."},
        "rounds": 1,
    },
    {
        "id": "ru_14",
        "type": "rule",
        "title": {"en": "Phone Lockdown", "es": "Sin Celulares"},
        "description": {
            "en": "Absolutely no phones allowed for the next 3 rounds. Anyone caught touching their phone drinks immediately.",
            "es": "Absolutamente prohibido el celular por las próximas 3 rondas. Quien sea cachado tocando su celular, toma de inmediato.",
        },
        "consequence": {"en": "Touch your phone, drink.", "es": "Tocas tu celular, tomas."},
        "rounds": 3,
    },
    {
        "id": "ru_15",
        "type": "rule",
        "title": {"en": "Captain's Orders", "es": "Órdenes del Capitán"},
        "description": {
            "en": "Choose one player as Captain right now. Everyone must follow any order the Captain gives for the next 2 rounds.",
            "es": "Elijan a un jugador como Capitán ahora mismo. Todos deben obedecer cualquier orden del Capitán por las próximas 2 rondas.",
        },
        "consequence": {"en": "Disobey the Captain, drink.", "es": "Si desobedeces al Capitán, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_16",
        "type": "rule",
        "title": {"en": "Mirror Mirror", "es": "Espejito Espejito"},
        "description": {
            "en": "For the next round, each player must physically mirror all movements of the person directly to their right.",
            "es": "Por la próxima ronda, cada jugador debe imitar físicamente todos los movimientos de la persona a su derecha.",
        },
        "consequence": {"en": "Break the mirror, drink.", "es": "Rompes el espejo, tomas."},
        "rounds": 1,
    },
    {
        "id": "ru_17",
        "type": "rule",
        "title": {"en": "Compliment First", "es": "Primero el Halago"},
        "description": {
            "en": "Every sentence spoken must begin with a genuine compliment for the next 2 rounds. Skip it and drink.",
            "es": "Toda oración dicha debe empezar con un halago genuino por las próximas 2 rondas. Si te lo saltas, tomas.",
        },
        "consequence": {"en": "No compliment, drink.", "es": "Sin halago, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_18",
        "type": "rule",
        "title": {"en": "Last Names Only", "es": "Solo Apellidos"},
        "description": {
            "en": "First names are completely banned for the next 3 rounds. Last names or group-assigned titles only.",
            "es": "Los nombres de pila están totalmente prohibidos por las próximas 3 rondas. Solo apellidos o títulos asignados por el grupo.",
        },
        "consequence": {"en": "Use a first name, drink.", "es": "Si usas un nombre, tomas."},
        "rounds": 3,
    },
    {
        "id": "ru_19",
        "type": "rule",
        "title": {"en": "Full Volume", "es": "Volumen Máximo"},
        "description": {
            "en": "Everyone must speak at maximum, outdoor volume for the next entire round. Too quiet? Drink.",
            "es": "Todos deben hablar al volumen máximo, como afuera, durante toda la próxima ronda. ¿Muy bajo? Tomas.",
        },
        "consequence": {"en": "Speak softly, drink.", "es": "Hablas bajo, tomas."},
        "rounds": 1,
    },
    {
        "id": "ru_20",
        "type": "rule",
        "title": {"en": "Questions Only", "es": "Solo Preguntas"},
        "description": {
            "en": "Communication can only happen through questions for the next 2 rounds. Make a statement and you drink.",
            "es": "La comunicación solo puede ser por medio de preguntas en las próximas 2 rondas. Si haces una afirmación, tomas.",
        },
        "consequence": {"en": "Make a statement, drink.", "es": "Haces una afirmación, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_21",
        "type": "rule",
        "title": {"en": "Animal Sound", "es": "Sonido Animal"},
        "description": {
            "en": "End every sentence with the same animal sound for the next 2 rounds. Group picks the animal.",
            "es": "Termina cada oración con el mismo sonido animal por las próximas 2 rondas. El grupo escoge el animal.",
        },
        "consequence": {"en": "Skip the sound, drink.", "es": "Si te saltas el sonido, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_22",
        "type": "rule",
        "title": {"en": "Hand Up to Speak", "es": "Mano Arriba para Hablar"},
        "description": {
            "en": "For the next 2 rounds, you must raise your hand and wait to be called on before saying anything.",
            "es": "Por las próximas 2 rondas, debes levantar la mano y esperar a que te den la palabra antes de decir cualquier cosa.",
        },
        "consequence": {"en": "Talk out of turn, drink.", "es": "Hablas sin turno, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_23",
        "type": "rule",
        "title": {"en": "Eye Contact Only", "es": "Solo Contacto Visual"},
        "description": {
            "en": "When you speak for the next 2 rounds, you must lock eye contact with someone. Looking away costs a drink.",
            "es": "Cuando hables en las próximas 2 rondas, debes mantener contacto visual con alguien. Mirar a otro lado cuesta un trago.",
        },
        "consequence": {"en": "Break eye contact, drink.", "es": "Rompes contacto visual, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_24",
        "type": "rule",
        "title": {"en": "Sing Your Words", "es": "Canta tus Palabras"},
        "description": {
            "en": "For the entire next round, no one can speak normally — every sentence must be sung. Spoken word = drink.",
            "es": "Por toda la próxima ronda, nadie puede hablar normalmente — cada oración debe ser cantada. Palabra hablada = tomas.",
        },
        "consequence": {"en": "Speak instead of sing, drink.", "es": "Hablas en lugar de cantar, tomas."},
        "rounds": 1,
    },
    {
        "id": "ru_25",
        "type": "rule",
        "title": {"en": "Pirate Mode", "es": "Modo Pirata"},
        "description": {
            "en": "Everyone must speak like a pirate for the next 2 rounds. Arrr-rrgh required regularly. Forget and you drink.",
            "es": "Todos deben hablar como pirata por las próximas 2 rondas. ¡Arrr! es obligatorio cada tanto. Si lo olvidas, tomas.",
        },
        "consequence": {"en": "Drop the pirate, drink.", "es": "Si sueltas al pirata, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_26",
        "type": "rule",
        "title": {"en": "No I", "es": "Sin 'Yo'"},
        "description": {
            "en": "The word 'I' is completely banned for the next 2 rounds. Refer to yourself by name instead.",
            "es": "La palabra 'yo' está totalmente prohibida por las próximas 2 rondas. Refiérete a ti mismo por tu nombre.",
        },
        "consequence": {"en": "Say I, drink.", "es": "Si dices 'yo', tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_27",
        "type": "rule",
        "title": {"en": "No Yes Or No", "es": "Sin Sí ni No"},
        "description": {
            "en": "The words 'yes' and 'no' are banned for the next 2 rounds. Find creative ways to answer questions.",
            "es": "Las palabras 'sí' y 'no' están prohibidas por las próximas 2 rondas. Busca formas creativas de responder.",
        },
        "consequence": {"en": "Slip and drink.", "es": "Si fallas, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_28",
        "type": "rule",
        "title": {"en": "Royalty Mode", "es": "Modo Realeza"},
        "description": {
            "en": "Everyone is now royalty. Address each other only as 'your majesty' or 'your highness' for 2 rounds.",
            "es": "Todos ahora son realeza. Dirígete a los demás solo como 'su majestad' o 'su alteza' por 2 rondas.",
        },
        "consequence": {"en": "Drop the title, drink.", "es": "Si sueltas el título, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_29",
        "type": "rule",
        "title": {"en": "Crouch to Drink", "es": "Agacharse para Beber"},
        "description": {
            "en": "For the next 2 rounds, every drink must be taken in a deep crouch position. Standing sip = drink twice.",
            "es": "Por las próximas 2 rondas, todo trago debe tomarse en cuclillas profundas. Sorbo de pie = tomas dos veces.",
        },
        "consequence": {"en": "Standing sip, drink twice.", "es": "Sorbo de pie, tomas dos veces."},
        "rounds": 2,
    },
    {
        "id": "ru_30",
        "type": "rule",
        "title": {"en": "Yoda Speak", "es": "Habla Yoda"},
        "description": {
            "en": "For the next 2 rounds, you must speak in Yoda-style inverted sentences. Normal grammar = drink.",
            "es": "Por las próximas 2 rondas, debes hablar al estilo de Yoda con oraciones invertidas. Gramática normal = tomas.",
        },
        "consequence": {"en": "Speak normally, drink.", "es": "Hablas normal, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_31",
        "type": "rule",
        "title": {"en": "No Pronouns", "es": "Sin Pronombres"},
        "description": {
            "en": "All personal pronouns are banned for the next 2 rounds. Use full names or nouns only.",
            "es": "Todos los pronombres personales están prohibidos por las próximas 2 rondas. Solo usa nombres completos o sustantivos.",
        },
        "consequence": {"en": "Use a pronoun, drink.", "es": "Si usas un pronombre, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_32",
        "type": "rule",
        "title": {"en": "Always Smile", "es": "Siempre Sonríe"},
        "description": {
            "en": "Everyone must keep a wide smile while speaking for the next 2 rounds. Frown or neutral = drink.",
            "es": "Todos deben mantener una sonrisa amplia mientras hablan por las próximas 2 rondas. Cara seria o neutra = tomas.",
        },
        "consequence": {"en": "Drop the smile, drink.", "es": "Si bajas la sonrisa, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_33",
        "type": "rule",
        "title": {"en": "Salute Drinks", "es": "Saludo Militar"},
        "description": {
            "en": "Before any sip for the next 2 rounds, you must give a full military salute. Forget = drink twice.",
            "es": "Antes de cualquier sorbo por las próximas 2 rondas, debes hacer un saludo militar completo. Si olvidas = tomas dos veces.",
        },
        "consequence": {"en": "Forget the salute, drink twice.", "es": "Olvidas el saludo, tomas dos veces."},
        "rounds": 2,
    },
    {
        "id": "ru_34",
        "type": "rule",
        "title": {"en": "Foot Tap", "es": "Pie Marcando"},
        "description": {
            "en": "Everyone must continuously tap one foot for the entire next round. Stop tapping = drink.",
            "es": "Todos deben marcar continuamente con un pie durante toda la próxima ronda. Si paras = tomas.",
        },
        "consequence": {"en": "Stop tapping, drink.", "es": "Si paras, tomas."},
        "rounds": 1,
    },
    {
        "id": "ru_35",
        "type": "rule",
        "title": {"en": "Dance Reply", "es": "Respuesta Bailando"},
        "description": {
            "en": "Every question for the next 2 rounds must be answered by first doing a dance move, then speaking.",
            "es": "Toda pregunta en las próximas 2 rondas debe responderse haciendo primero un paso de baile, luego hablando.",
        },
        "consequence": {"en": "Skip the dance, drink.", "es": "Si te saltas el baile, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_36",
        "type": "rule",
        "title": {"en": "Whisper Names", "es": "Susurrar Nombres"},
        "description": {
            "en": "Names of all players must always be whispered for the next 2 rounds, even mid-sentence.",
            "es": "Los nombres de todos los jugadores deben susurrarse siempre por las próximas 2 rondas, incluso a mitad de oración.",
        },
        "consequence": {"en": "Loud name, drink.", "es": "Nombre fuerte, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_37",
        "type": "rule",
        "title": {"en": "Crawl Mode", "es": "Modo Arrastrarse"},
        "description": {
            "en": "For the next round, no one can stand or walk normally. Move only by crawling on hands and knees.",
            "es": "Por la próxima ronda, nadie puede pararse ni caminar normalmente. Solo se mueven gateando en manos y rodillas.",
        },
        "consequence": {"en": "Stand up, drink.", "es": "Si te paras, tomas."},
        "rounds": 1,
    },
    {
        "id": "ru_38",
        "type": "rule",
        "title": {"en": "Mute Player", "es": "Jugador Mudo"},
        "description": {
            "en": "Pick one player right now. They cannot speak at all for the next 2 rounds. Speaking = drink twice.",
            "es": "Escojan un jugador ahora mismo. No puede hablar para nada por las próximas 2 rondas. Hablar = tomar dos veces.",
        },
        "consequence": {"en": "Mute speaks, drink twice.", "es": "El mudo habla, toma dos veces."},
        "rounds": 2,
    },
    {
        "id": "ru_39",
        "type": "rule",
        "title": {"en": "Raspy Voice", "es": "Voz Ronca"},
        "description": {
            "en": "Everyone must speak only in a raspy half-voice for the next 2 rounds. Normal voice = drink.",
            "es": "Todos deben hablar solo con una voz ronca a media potencia por las próximas 2 rondas. Voz normal = tomas.",
        },
        "consequence": {"en": "Normal voice, drink.", "es": "Voz normal, tomas."},
        "rounds": 2,
    },
    {
        "id": "ru_40",
        "type": "rule",
        "title": {"en": "Thumbs Hidden", "es": "Pulgares Ocultos"},
        "description": {
            "en": "Both thumbs must be tucked into your fists for the entire next round. Visible thumb = drink.",
            "es": "Ambos pulgares deben estar metidos en los puños durante toda la próxima ronda. Pulgar visible = tomas.",
        },
        "consequence": {"en": "Show a thumb, drink.", "es": "Muestras un pulgar, tomas."},
        "rounds": 1,
    },
]

PENALTY_CARDS = [
    {
        "id": "pe_01",
        "type": "penalty",
        "title": {"en": "No Excuses", "es": "Sin Excusas"},
        "description": {
            "en": "Take a full shot right now. No negotiating, no skipping, no water swaps.",
            "es": "Tómate un shot completo ahora mismo. Sin negociar, sin saltártelo, sin cambiarlo por agua.",
        },
        "drink_amount": "shot",
    },
    {
        "id": "pe_02",
        "type": "penalty",
        "title": {"en": "Half Way There", "es": "A Mitad de Camino"},
        "description": {
            "en": "Drink exactly half your glass right now. No sipping — take it properly.",
            "es": "Tómate exactamente medio vaso ahora mismo. Sin sorbitos — hazlo bien.",
        },
        "drink_amount": "half_glass",
    },
    {
        "id": "pe_03",
        "type": "penalty",
        "title": {"en": "Bottoms Up", "es": "Hasta el Fondo"},
        "description": {
            "en": "Finish your entire drink. Every last drop. Slam it down when you're done.",
            "es": "Termina toda tu bebida. Hasta la última gota. Golpea el vaso cuando termines.",
        },
        "drink_amount": "full_glass",
    },
    {
        "id": "pe_04",
        "type": "penalty",
        "title": {"en": "Fun Tax", "es": "Impuesto a la Diversión"},
        "description": {
            "en": "Look around the group and choose whoever is having the most fun tonight. They drink 2 sips.",
            "es": "Mira al grupo y elige a quien se la esté pasando mejor esta noche. Esa persona toma 2 sorbos.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_05",
        "type": "penalty",
        "title": {"en": "Left Neighbor", "es": "Vecino de la Izquierda"},
        "description": {
            "en": "The person sitting directly to your left drinks a full sip. They have no say in the matter.",
            "es": "La persona a tu izquierda toma un sorbo completo. No tiene voto en el asunto.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_06",
        "type": "penalty",
        "title": {"en": "Right Neighbor", "es": "Vecino de la Derecha"},
        "description": {
            "en": "The person sitting directly to your right drinks a full sip. Sorry, not sorry.",
            "es": "La persona a tu derecha toma un sorbo completo. Lo siento, no lo siento.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_07",
        "type": "penalty",
        "title": {"en": "Cheers Everyone", "es": "Salud para Todos"},
        "description": {
            "en": "Everyone picks up their drink and drinks together on the count of three. Cheers!",
            "es": "Todos levantan su bebida y toman juntos a la cuenta de tres. ¡Salud!",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_08",
        "type": "penalty",
        "title": {"en": "Last One Standing", "es": "Último en Pie"},
        "description": {
            "en": "Everyone starts drinking at the same time. The last person to finish their sip takes another sip.",
            "es": "Todos empiezan a tomar al mismo tiempo. La última persona en terminar su sorbo toma otro sorbo.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_09",
        "type": "penalty",
        "title": {"en": "Three Sips Rule", "es": "Regla de Tres Sorbos"},
        "description": {
            "en": "Take exactly three sips of your drink right now. Not one, not two — three.",
            "es": "Toma exactamente tres sorbos de tu bebida ahora mismo. Ni uno, ni dos — tres.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_10",
        "type": "penalty",
        "title": {"en": "Diagonal Duo", "es": "Dúo Diagonal"},
        "description": {
            "en": "You and the person diagonally across from you must both drink a full sip simultaneously.",
            "es": "Tú y la persona en diagonal frente a ti deben tomar un sorbo completo al mismo tiempo.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_11",
        "type": "penalty",
        "title": {"en": "Social Round", "es": "Ronda Social"},
        "description": {
            "en": "On the count of three, absolutely everyone at the table takes one sip simultaneously.",
            "es": "A la cuenta de tres, absolutamente todos en la mesa toman un sorbo al mismo tiempo.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_12",
        "type": "penalty",
        "title": {"en": "Waterfall", "es": "Cascada"},
        "description": {
            "en": "Everyone starts drinking together. You stop first, then the next person clockwise stops, and so on around the table.",
            "es": "Todos empiezan a tomar juntos. Tú paras primero, luego la siguiente persona en sentido horario, y así por toda la mesa.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_13",
        "type": "penalty",
        "title": {"en": "Youth Penalty", "es": "Penalidad de Juventud"},
        "description": {
            "en": "The youngest player at the table drinks a full shot right now. Age has consequences.",
            "es": "El jugador más joven de la mesa toma un shot completo ahora mismo. La edad tiene consecuencias.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_14",
        "type": "penalty",
        "title": {"en": "Experience Tax", "es": "Impuesto a la Experiencia"},
        "description": {
            "en": "The oldest player at the table drinks a full shot right now. Respect comes with a price.",
            "es": "El jugador mayor de la mesa toma un shot completo ahora mismo. El respeto tiene su precio.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_15",
        "type": "penalty",
        "title": {"en": "Four Eyes", "es": "Cuatro Ojos"},
        "description": {
            "en": "Anyone currently wearing glasses of any kind must drink immediately. Contacts don't count.",
            "es": "Quien esté usando lentes de cualquier tipo debe tomar inmediatamente. Los lentes de contacto no cuentan.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_16",
        "type": "penalty",
        "title": {"en": "Double Shot", "es": "Shot Doble"},
        "description": {
            "en": "Take two shots back to back with no break between them. No chaser until both are down.",
            "es": "Tómate dos shots seguidos sin pausa entre ellos. Nada de chaser hasta bajarlos los dos.",
        },
        "drink_amount": "shot",
    },
    {
        "id": "pe_17",
        "type": "penalty",
        "title": {"en": "Dealer's Tax", "es": "Impuesto del Repartidor"},
        "description": {
            "en": "The current card dealer (the one who drew this card) drinks a full shot. Karma is swift.",
            "es": "El repartidor actual de cartas (el que sacó esta carta) toma un shot completo. El karma es rápido.",
        },
        "drink_amount": "shot",
    },
    {
        "id": "pe_18",
        "type": "penalty",
        "title": {"en": "Phone Patrol", "es": "Patrulla del Celular"},
        "description": {
            "en": "Anyone currently on their phone or who has touched their phone in the last 2 minutes drinks now.",
            "es": "Quien esté en su celular o haya tocado su celular en los últimos 2 minutos, toma ahora.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_19",
        "type": "penalty",
        "title": {"en": "Sober Award", "es": "Premio al Más Sobrio"},
        "description": {
            "en": "The group votes on who looks the most sober right now. Majority rules. That person drinks.",
            "es": "El grupo vota quién se ve más sobrio ahora mismo. Mayoría decide. Esa persona toma.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_20",
        "type": "penalty",
        "title": {"en": "Democracy Drinks", "es": "Democracia Líquida"},
        "description": {
            "en": "Everyone votes on one person who should drink. Majority wins with no appeals. You know who you are.",
            "es": "Todos votan por una persona que deba tomar. La mayoría gana sin apelaciones. Ya saben quién es.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_21",
        "type": "penalty",
        "title": {"en": "Toast Master", "es": "Maestro del Brindis"},
        "description": {
            "en": "Stand up and propose a heartfelt toast to the group. Everyone drinks once you finish.",
            "es": "Ponte de pie y propón un brindis sincero al grupo. Todos toman cuando termines.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_22",
        "type": "penalty",
        "title": {"en": "Loser's Lap", "es": "Vuelta del Perdedor"},
        "description": {
            "en": "Run a full lap around the room or table right now. Then drink half your glass. No walking.",
            "es": "Da una vuelta completa al cuarto o a la mesa ahora mismo. Después toma medio vaso. Sin caminar.",
        },
        "drink_amount": "half_glass",
    },
    {
        "id": "pe_23",
        "type": "penalty",
        "title": {"en": "Two Big Gulps", "es": "Dos Tragazos"},
        "description": {
            "en": "Take two big, committed gulps of your drink in a row. No tiny sips, the group counts.",
            "es": "Date dos tragazos grandes y comprometidos de tu bebida seguidos. Nada de sorbitos, el grupo cuenta.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_24",
        "type": "penalty",
        "title": {"en": "Tallest Drinks", "es": "El Más Alto Toma"},
        "description": {
            "en": "The tallest player at the table drinks a full sip right now. Genetics is unforgiving.",
            "es": "El jugador más alto de la mesa toma un sorbo completo ahora mismo. La genética no perdona.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_25",
        "type": "penalty",
        "title": {"en": "Shortest Drinks", "es": "El Más Bajo Toma"},
        "description": {
            "en": "The shortest player at the table drinks a full sip right now. Size matters tonight.",
            "es": "El jugador más bajo de la mesa toma un sorbo completo ahora mismo. El tamaño importa esta noche.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_26",
        "type": "penalty",
        "title": {"en": "Long Hair", "es": "Cabello Largo"},
        "description": {
            "en": "The player with the longest hair at the table drinks a full sip. No measuring debates.",
            "es": "El jugador con el cabello más largo de la mesa toma un sorbo completo. Sin debates de medición.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_27",
        "type": "penalty",
        "title": {"en": "Closest Birthday", "es": "Cumpleaños Cercano"},
        "description": {
            "en": "Whoever's birthday is coming up next on the calendar drinks a full sip. Time to celebrate early.",
            "es": "Quien tenga el siguiente cumpleaños en el calendario toma un sorbo completo. A celebrar antes.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_28",
        "type": "penalty",
        "title": {"en": "Most Tattoos", "es": "Más Tatuajes"},
        "description": {
            "en": "The player with the most visible tattoos drinks a full shot. Body art has consequences.",
            "es": "El jugador con más tatuajes visibles toma un shot completo. El arte corporal tiene consecuencias.",
        },
        "drink_amount": "shot",
    },
    {
        "id": "pe_29",
        "type": "penalty",
        "title": {"en": "Dance Penalty", "es": "Penalidad Bailable"},
        "description": {
            "en": "Dance for 10 full seconds in front of the group, then take a full sip. No rhythm required.",
            "es": "Baila 10 segundos completos frente al grupo, luego toma un sorbo completo. No se necesita ritmo.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_30",
        "type": "penalty",
        "title": {"en": "Sing Before Drink", "es": "Canta antes de Beber"},
        "description": {
            "en": "Sing one full line of any song out loud, then take a sip. No mumbling allowed.",
            "es": "Canta una línea completa de cualquier canción en voz alta, luego toma un sorbo. Sin balbucear.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_31",
        "type": "penalty",
        "title": {"en": "Switch Drinks", "es": "Cambia Bebida"},
        "description": {
            "en": "Swap your drink with the player to your left for the next 3 rounds. No backsies.",
            "es": "Intercambia tu bebida con el jugador a tu izquierda por las próximas 3 rondas. Sin reclamos.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_32",
        "type": "penalty",
        "title": {"en": "Eye Contact Drink", "es": "Contacto Visual"},
        "description": {
            "en": "Pick a player and lock eyes with them. Take a full sip while holding the eye contact unbroken.",
            "es": "Escoge un jugador y mantén el contacto visual. Toma un sorbo completo sin romper la mirada.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_33",
        "type": "penalty",
        "title": {"en": "Standing Drink", "es": "Beber de Pie"},
        "description": {
            "en": "Everyone stands up right now. Last one on their feet drinks twice. Quick reflexes wanted.",
            "es": "Todos se ponen de pie ahora mismo. El último en pararse toma dos veces. Reflejos rápidos requeridos.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_34",
        "type": "penalty",
        "title": {"en": "Pinky Up", "es": "Meñique Arriba"},
        "description": {
            "en": "Take a full sip with your pinky finger raised like royalty. Pinky drops = drink twice.",
            "es": "Toma un sorbo completo con el meñique levantado como realeza. Si baja el meñique = tomas dos veces.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_35",
        "type": "penalty",
        "title": {"en": "Joker's Penalty", "es": "Penalidad del Bromista"},
        "description": {
            "en": "Whoever made the last joke that got a real laugh drinks a full sip. Comedy isn't free.",
            "es": "Quien hizo el último chiste que sacó una risa de verdad toma un sorbo completo. La comedia no es gratis.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_36",
        "type": "penalty",
        "title": {"en": "Selfie Time", "es": "Hora del Selfie"},
        "description": {
            "en": "Take an absolutely ridiculous group selfie right now, then everyone in the photo drinks once.",
            "es": "Tomen una selfie grupal totalmente ridícula ahora mismo, luego todos los de la foto toman una vez.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_37",
        "type": "penalty",
        "title": {"en": "Loud Cheers", "es": "Brindis Fuerte"},
        "description": {
            "en": "Everyone shouts 'cheers!' as loudly as they can on three, then drinks. Quietest one drinks again.",
            "es": "Todos gritan '¡salud!' tan fuerte como puedan a la cuenta de tres, luego toman. El más callado toma de nuevo.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_38",
        "type": "penalty",
        "title": {"en": "Coin Flip", "es": "Cara o Sello"},
        "description": {
            "en": "Flip a coin. Heads, the entire group drinks. Tails, you take a full shot. Fate decides.",
            "es": "Lanza una moneda. Cara, todo el grupo toma. Sello, tú te tomas un shot completo. El destino decide.",
        },
        "drink_amount": "none",
    },
    {
        "id": "pe_39",
        "type": "penalty",
        "title": {"en": "Truth Trade", "es": "Trueque de Verdad"},
        "description": {
            "en": "Tell the group one embarrassing fact about yourself right now, or take a full shot.",
            "es": "Cuéntale al grupo un dato vergonzoso de ti mismo ahora mismo, o tómate un shot completo.",
        },
        "drink_amount": "shot",
    },
    {
        "id": "pe_40",
        "type": "penalty",
        "title": {"en": "Group Picks", "es": "El Grupo Elige"},
        "description": {
            "en": "The group chooses one player who must drink twice. Most votes wins, no appeals allowed.",
            "es": "El grupo elige un jugador que debe tomar dos veces. Más votos gana, sin apelaciones.",
        },
        "drink_amount": "none",
    },
]

ALL_CARDS = CHALLENGE_CARDS + TRUTH_CARDS + RULE_CARDS + PENALTY_CARDS
