CHALLENGE_CARDS = [
    {"id": "ch_01", "type": "challenge", "title": "Steady Hands", "description": "Balance a coin on your nose for 10 seconds without it falling.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_02", "type": "challenge", "title": "Twisted Tongue", "description": "Say 'She sells seashells by the seashore' three times fast without messing up.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_03", "type": "challenge", "title": "Iron Body", "description": "Hold a perfect plank position for 30 seconds. No sagging, no cheating.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_04", "type": "challenge", "title": "Spin Zone", "description": "Spin around 5 times with your eyes closed, then walk in a perfectly straight line.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_05", "type": "challenge", "title": "Wild Animal", "description": "Imitate an animal of the group's choice for 30 full seconds without stopping.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_06", "type": "challenge", "title": "Sing It", "description": "Sing the full chorus of any song of your choice out loud — no humming.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_07", "type": "challenge", "title": "Robot Mode", "description": "Do your best robot dance for 20 full seconds. Group votes if it counts.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_08", "type": "challenge", "title": "Alphabet Backwards", "description": "Say the entire alphabet backwards in under 30 seconds. One mistake and you're done.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_09", "type": "challenge", "title": "Wall Sit", "description": "Hold a wall sit (90-degree angle) for 30 seconds. No pushing off the wall.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_10", "type": "challenge", "title": "Who Am I?", "description": "Imitate someone in the room until the group correctly guesses who you're impersonating.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_11", "type": "challenge", "title": "Red Lorry", "description": "Say 'red lorry, yellow lorry' five times fast. One slip and you drink.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_12", "type": "challenge", "title": "Jump Squad", "description": "Do 15 jumping jacks in a row without stopping. No half-reps.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_13", "type": "challenge", "title": "Flamingo", "description": "Balance on one foot for 30 seconds without touching anything for support.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_14", "type": "challenge", "title": "Geography Genius", "description": "Name 10 different countries in 15 seconds. Group decides if they count.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_15", "type": "challenge", "title": "Runway Walk", "description": "Do a full catwalk across the room and back like a supermodel. Own it.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_16", "type": "challenge", "title": "Mystery Tune", "description": "Whistle a song while others try to guess it. If nobody guesses in 30 seconds, you drink.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_17", "type": "challenge", "title": "Breath Control", "description": "Hold your breath for a full 20 seconds. Group counts out loud.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_18", "type": "challenge", "title": "Drama Star", "description": "Give a dramatic 20-second monologue about any mundane part of your day.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_19", "type": "challenge", "title": "Burpee Time", "description": "Do 5 clean burpees right now. Chest to floor, full jump. No shortcuts.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_20", "type": "challenge", "title": "Fame Drop", "description": "Name 10 different celebrities in 15 seconds. Group votes on if they're real.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_21", "type": "challenge", "title": "The Worm", "description": "Do the worm across the floor — or at least a sincere attempt. Group decides.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_22", "type": "challenge", "title": "Elbow Catch", "description": "Stack 5 coins on your elbow and swing your arm to catch them all in one move.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_23", "type": "challenge", "title": "Unique New York", "description": "Say 'unique New York' five times fast without stumbling once.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_24", "type": "challenge", "title": "Moonwalk", "description": "Do your best Michael Jackson moonwalk across the room. Technique counts.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_25", "type": "challenge", "title": "Head Balancer", "description": "Balance any object from your surroundings on your head for 30 seconds.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_26", "type": "challenge", "title": "Squat Squad", "description": "Do 10 full squats in a row with proper form. Thighs parallel or you redo it.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_27", "type": "challenge", "title": "Nursery Rhyme", "description": "Recite any nursery rhyme fully from memory. No pausing, no helping.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_28", "type": "challenge", "title": "Hype Dance", "description": "Do your most energetic hype dance move for 15 full seconds. Go all in.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "ch_29", "type": "challenge", "title": "Core Challenge", "description": "Do 10 proper sit-ups in a row. Hands behind your head, back to floor each rep.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "ch_30", "type": "challenge", "title": "Comedian", "description": "Make at least one person in the group genuinely laugh in 30 seconds.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
]

TRUTH_CARDS = [
    {"id": "tr_01", "type": "truth", "title": "Public Shame", "description": "What's the most embarrassing thing you've done in public? Give full details.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_02", "type": "truth", "title": "Dating Lies", "description": "Have you ever lied to get out of a date? What was the lie and who was the victim?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_03", "type": "truth", "title": "Worst Date Ever", "description": "Describe the absolute worst date you've ever been on. What made it so terrible?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_04", "type": "truth", "title": "Social Stalker", "description": "Have you ever stalked someone's social media for more than an hour straight? Who and why?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_05", "type": "truth", "title": "Search History", "description": "What's the most embarrassing thing currently in your search history? No lying.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_06", "type": "truth", "title": "Wrong Text", "description": "Have you ever sent a message to the completely wrong person? What did it say?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_07", "type": "truth", "title": "Parent Lies", "description": "What's the biggest lie you've ever told your parents? Did they ever find out?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_08", "type": "truth", "title": "Pool Confession", "description": "Have you ever peed in a pool or a body of water? Be completely honest.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_09", "type": "truth", "title": "Forever Young", "description": "What's the most childish thing you still secretly do that you'd be embarrassed if people knew?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_10", "type": "truth", "title": "Forbidden Crush", "description": "Have you ever had romantic feelings for a close friend's significant other?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_11", "type": "truth", "title": "Drunk Story", "description": "What's the most embarrassing thing you've done while drunk? Full story.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_12", "type": "truth", "title": "Academic Crime", "description": "Have you ever cheated on a test, exam, or major assignment? Tell the story.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_13", "type": "truth", "title": "Home Alone Weirdness", "description": "What's the weirdest thing you do when you're completely alone at home?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_14", "type": "truth", "title": "Ghost Mode", "description": "Have you ever ghosted someone you actually had feelings for? What happened?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_15", "type": "truth", "title": "Guilty Playlist", "description": "What's the most embarrassing song you genuinely love and listen to on repeat?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_16", "type": "truth", "title": "Fake Laugh", "description": "When was the last time you pretended to laugh at a joke you didn't understand at all?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_17", "type": "truth", "title": "Behind The Back", "description": "What's the worst thing you've ever said about someone in this room behind their back?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_18", "type": "truth", "title": "Wrong Bathroom", "description": "Have you ever accidentally walked into the wrong bathroom? Tell the whole story.", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_19", "type": "truth", "title": "Dirty Habit", "description": "What habit are you most embarrassed about? Something you'd never admit sober.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_20", "type": "truth", "title": "Awkward Nap", "description": "Have you ever fallen asleep somewhere truly embarrassing or inappropriate? Where?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_21", "type": "truth", "title": "Cringe Moment", "description": "What's the most awkward social situation you've ever been stuck in?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_22", "type": "truth", "title": "Accidental Like", "description": "Have you ever accidentally liked a very old post while deep-stalking someone online?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_23", "type": "truth", "title": "Photo Shame", "description": "Describe the most embarrassing photo of you that exists somewhere right now.", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_24", "type": "truth", "title": "Age Faker", "description": "Have you ever lied about your age to get into somewhere or impress someone?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_25", "type": "truth", "title": "Old But Gold", "description": "What's something you're definitely too old for but still secretly enjoy doing?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_26", "type": "truth", "title": "Caught Red-Handed", "description": "What's the most embarrassing thing you've been caught doing that you had no excuse for?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_27", "type": "truth", "title": "Terrible Gift", "description": "What's the most thoughtless or terrible gift you've ever given someone? Who got it?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_28", "type": "truth", "title": "Soft Heart", "description": "What movie, TV show, or book made you cry that most people would find embarrassing?", "consequence": "Take a full shot.", "drink_amount": "shot"},
    {"id": "tr_29", "type": "truth", "title": "Attention Seeker", "description": "What's the most desperate thing you've ever done to get someone's attention?", "consequence": "Drink half your glass.", "drink_amount": "half_glass"},
    {"id": "tr_30", "type": "truth", "title": "Celebrity Claim", "description": "Have you ever pretended to personally know a celebrity or famous person?", "consequence": "Take a full shot.", "drink_amount": "shot"},
]

RULE_CARDS = [
    {"id": "ru_01", "type": "rule", "title": "No Real Names", "description": "No one can use anyone's real name for the next 3 rounds. Invent a nickname for everyone right now. Anyone who slips up drinks.", "consequence": "Slip up and drink.", "rounds": 3},
    {"id": "ru_02", "type": "rule", "title": "Whisper Mode", "description": "Everyone must whisper for the next 2 full rounds. Speaking at normal volume means you drink immediately.", "consequence": "Normal volume costs a drink.", "rounds": 2},
    {"id": "ru_03", "type": "rule", "title": "Elbow Pointers Only", "description": "No pointing with fingers for the next 3 rounds. Use your elbow to point. Anyone who points with a finger drinks.", "consequence": "Finger pointer drinks.", "rounds": 3},
    {"id": "ru_04", "type": "rule", "title": "In Bed Rule", "description": "Everyone must add 'in bed' to the end of every single sentence for the next 2 rounds.", "consequence": "Forget and drink.", "rounds": 2},
    {"id": "ru_05", "type": "rule", "title": "No Laughing", "description": "Absolutely no laughing allowed for the next 2 rounds. Anyone who laughs — even smiles — must drink.", "consequence": "Laugh and you drink.", "rounds": 2},
    {"id": "ru_06", "type": "rule", "title": "Accent Time", "description": "Everyone must pick an accent right now and speak in it for the next 3 rounds. Dropping the accent means a drink.", "consequence": "Drop the accent, drink.", "rounds": 3},
    {"id": "ru_07", "type": "rule", "title": "Left Hand Only", "description": "All drinks must be taken with the left hand for the next 3 rounds. Using the right hand means you drink again with the left.", "consequence": "Wrong hand? Drink again.", "rounds": 3},
    {"id": "ru_08", "type": "rule", "title": "May I Please?", "description": "No one may take a sip of any drink without first saying 'May I please have a sip?' for the next 2 rounds.", "consequence": "Skip the phrase, drink twice.", "rounds": 2},
    {"id": "ru_09", "type": "rule", "title": "Stand to Speak", "description": "For the next 2 rounds, anyone who wants to talk must stand up first. Speak while seated and you drink.", "consequence": "Sit and speak? Drink up.", "rounds": 2},
    {"id": "ru_10", "type": "rule", "title": "Banned Words", "description": "The words 'drink' and 'shot' are completely banned for the next 3 rounds. Invent code words. Anyone who slips drinks.", "consequence": "Say the word, drink.", "rounds": 3},
    {"id": "ru_11", "type": "rule", "title": "Rhyme Time", "description": "Every sentence must rhyme with the last word of the previous speaker for the next 2 rounds. Fail and drink.", "consequence": "No rhyme, drink.", "rounds": 2},
    {"id": "ru_12", "type": "rule", "title": "Robot Speak", "description": "Everyone must speak in a robotic, monotone voice for the next 2 rounds. Going human costs a drink.", "consequence": "Break character, drink.", "rounds": 2},
    {"id": "ru_13", "type": "rule", "title": "Slow Motion", "description": "Every physical movement must be done in slow motion for the entire next round. Speed up and you drink.", "consequence": "Move too fast, drink.", "rounds": 1},
    {"id": "ru_14", "type": "rule", "title": "Phone Lockdown", "description": "Absolutely no phones allowed for the next 3 rounds. Anyone caught touching their phone drinks immediately.", "consequence": "Touch your phone, drink.", "rounds": 3},
    {"id": "ru_15", "type": "rule", "title": "Captain's Orders", "description": "Choose one player as Captain right now. Everyone must follow any order the Captain gives for the next 2 rounds.", "consequence": "Disobey the Captain, drink.", "rounds": 2},
    {"id": "ru_16", "type": "rule", "title": "Mirror Mirror", "description": "For the next round, each player must physically mirror all movements of the person directly to their right.", "consequence": "Break the mirror, drink.", "rounds": 1},
    {"id": "ru_17", "type": "rule", "title": "Compliment First", "description": "Every sentence spoken must begin with a genuine compliment for the next 2 rounds. Skip it and drink.", "consequence": "No compliment, drink.", "rounds": 2},
    {"id": "ru_18", "type": "rule", "title": "Last Names Only", "description": "First names are completely banned for the next 3 rounds. Last names or group-assigned titles only.", "consequence": "Use a first name, drink.", "rounds": 3},
    {"id": "ru_19", "type": "rule", "title": "Full Volume", "description": "Everyone must speak at maximum, outdoor volume for the next entire round. Too quiet? Drink.", "consequence": "Speak softly, drink.", "rounds": 1},
    {"id": "ru_20", "type": "rule", "title": "Questions Only", "description": "Communication can only happen through questions for the next 2 rounds. Make a statement and you drink.", "consequence": "Make a statement, drink.", "rounds": 2},
]

PENALTY_CARDS = [
    {"id": "pe_01", "type": "penalty", "title": "No Excuses", "description": "Take a full shot right now. No negotiating, no skipping, no water swaps.", "drink_amount": "shot"},
    {"id": "pe_02", "type": "penalty", "title": "Half Way There", "description": "Drink exactly half your glass right now. No sipping — take it properly.", "drink_amount": "half_glass"},
    {"id": "pe_03", "type": "penalty", "title": "Bottom's Up", "description": "Finish your entire drink. Every last drop. Slam it down when you're done.", "drink_amount": "full_glass"},
    {"id": "pe_04", "type": "penalty", "title": "Fun Tax", "description": "Look around the group and choose whoever is having the most fun tonight. They drink 2 sips.", "drink_amount": "none"},
    {"id": "pe_05", "type": "penalty", "title": "Left Neighbor", "description": "The person sitting directly to your left drinks a full sip. They have no say in the matter.", "drink_amount": "none"},
    {"id": "pe_06", "type": "penalty", "title": "Right Neighbor", "description": "The person sitting directly to your right drinks a full sip. Sorry, not sorry.", "drink_amount": "none"},
    {"id": "pe_07", "type": "penalty", "title": "Cheers Everyone", "description": "Everyone picks up their drink and drinks together on the count of three. Cheers!", "drink_amount": "none"},
    {"id": "pe_08", "type": "penalty", "title": "Last One Standing", "description": "Everyone starts drinking at the same time. The last person to finish their sip takes another sip.", "drink_amount": "none"},
    {"id": "pe_09", "type": "penalty", "title": "Three Sips Rule", "description": "Take exactly three sips of your drink right now. Not one, not two — three.", "drink_amount": "none"},
    {"id": "pe_10", "type": "penalty", "title": "Diagonal Duo", "description": "You and the person diagonally across from you must both drink a full sip simultaneously.", "drink_amount": "none"},
    {"id": "pe_11", "type": "penalty", "title": "Social Round", "description": "On the count of three, absolutely everyone at the table takes one sip simultaneously.", "drink_amount": "none"},
    {"id": "pe_12", "type": "penalty", "title": "Waterfall", "description": "Everyone starts drinking together. You stop first, then the next person clockwise stops, and so on around the table.", "drink_amount": "none"},
    {"id": "pe_13", "type": "penalty", "title": "Youth Penalty", "description": "The youngest player at the table drinks a full shot right now. Age has consequences.", "drink_amount": "none"},
    {"id": "pe_14", "type": "penalty", "title": "Experience Tax", "description": "The oldest player at the table drinks a full shot right now. Respect comes with a price.", "drink_amount": "none"},
    {"id": "pe_15", "type": "penalty", "title": "Four Eyes", "description": "Anyone currently wearing glasses of any kind must drink immediately. Contacts don't count.", "drink_amount": "none"},
    {"id": "pe_16", "type": "penalty", "title": "Double Shot", "description": "Take two shots back to back with no break between them. No chaser until both are down.", "drink_amount": "shot"},
    {"id": "pe_17", "type": "penalty", "title": "Dealer's Tax", "description": "The current card dealer (the one who drew this card) drinks a full shot. Karma is swift.", "drink_amount": "shot"},
    {"id": "pe_18", "type": "penalty", "title": "Phone Patrol", "description": "Anyone currently on their phone or who has touched their phone in the last 2 minutes drinks now.", "drink_amount": "none"},
    {"id": "pe_19", "type": "penalty", "title": "Sober Award", "description": "The group votes on who looks the most sober right now. Majority rules. That person drinks.", "drink_amount": "none"},
    {"id": "pe_20", "type": "penalty", "title": "Democracy Drinks", "description": "Everyone votes on one person who should drink. Majority wins with no appeals. You know who you are.", "drink_amount": "none"},
]

ALL_CARDS = CHALLENGE_CARDS + TRUTH_CARDS + RULE_CARDS + PENALTY_CARDS
